<syntax> ::= <connection> "/" <table> "/" <column> <selectionStyle>
<connection> ::= "@" <connectionName>
	<connectionName> ::= <_text>
<table> ::= <tableName> <tableSelection> <tableQuery> | <tableName> <tableQuery> | <tableName>
	<tableName> ::= <_text>
	<tableSelection> ::= ":" <tableSelectionList>
		<tableSelectionList> ::= <tableSelectionItem> | <tableSelectionItem> <_owsp> "," <_owsp> <tableSelectionList>
		<tableSelectionItem> ::= <_text>
	<tableQuery> ::= "[" <_owsp> <tableQueryList> <_owsp> "]"
		<tableQueryList> ::= <tableStatment> | <tableStatment> <_wsp> <tableSeperator> <_wsp> <tableQueryList>
			<tableSeperator> ::= "and" | "or"
			<tableStatment> ::= <_text> <_owsp> <tableLogicSwitch> <_owsp> <_literal>
				<tableLogicSwitch> ::= "!=" | "="
	<column> ::= "" | #column
<selectionStyle> ::= <selectAll> | <selectFirst> | <selectExecute>
	<selectAll> ::= "*"
	<selectFirst> ::= "$"
	<selectExecute> ::= "!"